package org.wso2.dpdp.enf.dao.queries;

public class QueryConstants {

    private QueryConstants() {
    }

    // TOPIC Queries
    public static final String ADD_TOPIC =
            "INSERT INTO TOPIC (TOPIC_ID, ORG_ID, NAME, DESCRIPTION, STATUS) VALUES (?, ?, ?, ?, ?)";
    public static final String GET_TOPIC_BY_ID =
            "SELECT TOPIC_ID, ORG_ID, NAME, DESCRIPTION, STATUS FROM TOPIC WHERE TOPIC_ID = ?";
    public static final String GET_TOPIC_BY_ORG_AND_NAME =
            "SELECT TOPIC_ID, ORG_ID, NAME, DESCRIPTION, STATUS FROM TOPIC WHERE ORG_ID = ? AND NAME = ?";
    public static final String UPDATE_TOPIC_STATUS =
            "UPDATE TOPIC SET STATUS = ? WHERE TOPIC_ID = ?";

    // EVENT Queries
    public static final String ADD_EVENT =
            "INSERT INTO EVENT (EVENT_ID, ORG_ID, GROUP_ID, TOPIC_ID, PAYLOAD, CREATED_AT) VALUES (?, ?, ?, ?, ?, ?)";
    public static final String GET_EVENT_BY_ID =
            "SELECT EVENT_ID, ORG_ID, GROUP_ID, TOPIC_ID, PAYLOAD, CREATED_AT FROM EVENT WHERE EVENT_ID = ?";
    public static final String ADD_EVENT_PURPOSE =
            "INSERT INTO EVENT_PURPOSE (EVENT_ID, PURPOSE_NAME) VALUES (?, ?)";
    public static final String GET_EVENT_PURPOSES =
            "SELECT PURPOSE_NAME FROM EVENT_PURPOSE WHERE EVENT_ID = ?";

    // SUBSCRIPTION Queries
    public static final String ADD_SUBSCRIPTION =
            "INSERT INTO SUBSCRIPTION (SUBSCRIPTION_ID, ORG_ID, GROUP_ID, TOPIC_ID, STATUS, PURPOSE_FILTER_MODE, " +
            "CALLBACK_URL, SHARED_SECRET, CREATED_AT, UPDATED_AT, DELIVERY_MODE) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
    public static final String GET_SUBSCRIPTION_BY_ID =
            "SELECT SUBSCRIPTION_ID, ORG_ID, GROUP_ID, TOPIC_ID, STATUS, PURPOSE_FILTER_MODE, " +
            "CALLBACK_URL, SHARED_SECRET, CREATED_AT, UPDATED_AT, DELIVERY_MODE FROM SUBSCRIPTION WHERE SUBSCRIPTION_ID = ?";
    public static final String GET_SUBSCRIPTIONS_FOR_MATCHING =
            "SELECT SUBSCRIPTION_ID, ORG_ID, GROUP_ID, TOPIC_ID, STATUS, PURPOSE_FILTER_MODE, " +
            "CALLBACK_URL, SHARED_SECRET, CREATED_AT, UPDATED_AT, DELIVERY_MODE FROM SUBSCRIPTION " +
            "WHERE ORG_ID = ? AND GROUP_ID = ? AND TOPIC_ID = ? AND STATUS = 'active'";
    public static final String UPDATE_SUBSCRIPTION_STATUS =
            "UPDATE SUBSCRIPTION SET STATUS = ?, UPDATED_AT = CURRENT_TIMESTAMP WHERE SUBSCRIPTION_ID = ?";
    public static final String ADD_SUBSCRIPTION_PURPOSE =
            "INSERT INTO SUBSCRIPTION_PURPOSE (SUBSCRIPTION_ID, PURPOSE_NAME) VALUES (?, ?)";
    public static final String GET_SUBSCRIPTION_PURPOSES =
            "SELECT PURPOSE_NAME FROM SUBSCRIPTION_PURPOSE WHERE SUBSCRIPTION_ID = ?";
    public static final String GET_ACTIVE_PULL_SUBSCRIPTION_BY_GROUP =
            "SELECT SUBSCRIPTION_ID, ORG_ID, GROUP_ID, TOPIC_ID, STATUS, PURPOSE_FILTER_MODE, " +
            "CALLBACK_URL, SHARED_SECRET, CREATED_AT, UPDATED_AT, DELIVERY_MODE FROM SUBSCRIPTION " +
            "WHERE ORG_ID = ? AND GROUP_ID = ? AND STATUS = 'active' AND (LOWER(DELIVERY_MODE) = 'pull' OR LOWER(DELIVERY_MODE) = 'poll') LIMIT 1";

    // WEBHOOK_DELIVERY Queries
    public static final String ADD_WEBHOOK_DELIVERY =
            "INSERT INTO WEBHOOK_DELIVERY (DELIVERY_ID, SUBSCRIPTION_ID, EVENT_ID, STATUS, ATTEMPT_COUNT, " +
            "NEXT_RETRY_AT, CREATED_AT, UPDATED_AT, DELIVERED_AT) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
    public static final String GET_WEBHOOK_DELIVERY_BY_ID =
            "SELECT DELIVERY_ID, SUBSCRIPTION_ID, EVENT_ID, STATUS, ATTEMPT_COUNT, NEXT_RETRY_AT, CREATED_AT, UPDATED_AT, DELIVERED_AT " +
            "FROM WEBHOOK_DELIVERY WHERE DELIVERY_ID = ?";
    public static final String UPDATE_WEBHOOK_DELIVERY_STATUS =
            "UPDATE WEBHOOK_DELIVERY SET STATUS = ?, ATTEMPT_COUNT = ?, NEXT_RETRY_AT = ?, DELIVERED_AT = ?, " +
            "UPDATED_AT = CURRENT_TIMESTAMP WHERE DELIVERY_ID = ?";
    public static final String GET_PENDING_WEBHOOK_DELIVERIES =
            "SELECT DELIVERY_ID, SUBSCRIPTION_ID, EVENT_ID, STATUS, ATTEMPT_COUNT, NEXT_RETRY_AT, CREATED_AT, UPDATED_AT, DELIVERED_AT " +
            "FROM WEBHOOK_DELIVERY WHERE STATUS = 'pending' AND (NEXT_RETRY_AT IS NULL OR NEXT_RETRY_AT <= CURRENT_TIMESTAMP) " +
            "ORDER BY CREATED_AT ASC LIMIT ?";

    // WEBHOOK_DELIVERY_ACK Queries
    public static final String ADD_WEBHOOK_DELIVERY_ACK =
            "INSERT INTO WEBHOOK_DELIVERY_ACK (ACK_ID, DELIVERY_ID, COMPLETED_AT, COMPLETION_STATUS, COMPLETION_EVIDENCE) " +
            "VALUES (?, ?, ?, ?, ?)";
    public static final String GET_WEBHOOK_DELIVERY_ACK_BY_DELIVERY_ID =
            "SELECT ACK_ID, DELIVERY_ID, COMPLETED_AT, COMPLETION_STATUS, COMPLETION_EVIDENCE " +
            "FROM WEBHOOK_DELIVERY_ACK WHERE DELIVERY_ID = ?";

    // WEBHOOK_DELIVERY_AUDIT Queries
    public static final String ADD_WEBHOOK_DELIVERY_AUDIT =
            "INSERT INTO WEBHOOK_DELIVERY_AUDIT (AUDIT_ID, EVENT_ID, DELIVERY_ID, ORG_ID, RESPONSE_CODE, CREATED_AT, ATTEMPT_AT) " +
            "VALUES (?, ?, ?, ?, ?, ?, ?)";
    public static final String GET_WEBHOOK_DELIVERY_AUDITS_BY_DELIVERY_ID =
            "SELECT AUDIT_ID, EVENT_ID, DELIVERY_ID, ORG_ID, RESPONSE_CODE, CREATED_AT, ATTEMPT_AT " +
            "FROM WEBHOOK_DELIVERY_AUDIT WHERE DELIVERY_ID = ? ORDER BY ATTEMPT_AT ASC";

    // POLL_DELIVERY Queries
    public static final String ADD_POLL_DELIVERY =
            "INSERT INTO POLL_DELIVERY (DELIVERY_ID, SUBSCRIPTION_ID, EVENT_ID, STATUS, CREATED_AT, COMPLETED_AT) " +
            "VALUES (?, ?, ?, ?, ?, ?)";
    public static final String GET_PENDING_POLL_DELIVERIES =
            "SELECT DELIVERY_ID, SUBSCRIPTION_ID, EVENT_ID, STATUS, CREATED_AT, COMPLETED_AT " +
            "FROM POLL_DELIVERY WHERE SUBSCRIPTION_ID = ? AND STATUS = 'pending'";
    public static final String GET_POLL_DELIVERY_BY_ID =
            "SELECT DELIVERY_ID, SUBSCRIPTION_ID, EVENT_ID, STATUS, CREATED_AT, COMPLETED_AT " +
            "FROM POLL_DELIVERY WHERE DELIVERY_ID = ?";
    public static final String UPDATE_POLL_DELIVERY_STATUS =
            "UPDATE POLL_DELIVERY SET STATUS = ?, COMPLETED_AT = ? WHERE DELIVERY_ID = ?";

    // ORG_DELIVERY Queries
    public static final String GET_ORG_DELIVERIES_UNION_BASE =
            "SELECT d.DELIVERY_ID, d.EVENT_ID, d.SUBSCRIPTION_ID, t.NAME AS TOPIC_NAME, d.STATUS AS CURRENT_STATUS, 'WEBHOOK' AS DELIVERY_MODE, " +
            "e.CREATED_AT AS OCCURRED_AT, d.CREATED_AT AS DELIVERY_CREATED_AT, e.PAYLOAD AS PAYLOAD " +
            "FROM WEBHOOK_DELIVERY d " +
            "JOIN EVENT e ON d.EVENT_ID = e.EVENT_ID " +
            "JOIN TOPIC t ON e.TOPIC_ID = t.TOPIC_ID " +
            "JOIN SUBSCRIPTION s ON d.SUBSCRIPTION_ID = s.SUBSCRIPTION_ID " +
            "WHERE s.ORG_ID = ? " +
            "UNION ALL " +
            "SELECT p.DELIVERY_ID, p.EVENT_ID, p.SUBSCRIPTION_ID, t.NAME AS TOPIC_NAME, p.STATUS AS CURRENT_STATUS, 'POLL' AS DELIVERY_MODE, " +
            "e.CREATED_AT AS OCCURRED_AT, p.CREATED_AT AS DELIVERY_CREATED_AT, e.PAYLOAD AS PAYLOAD " +
            "FROM POLL_DELIVERY p " +
            "JOIN EVENT e ON p.EVENT_ID = e.EVENT_ID " +
            "JOIN TOPIC t ON e.TOPIC_ID = t.TOPIC_ID " +
            "JOIN SUBSCRIPTION s ON p.SUBSCRIPTION_ID = s.SUBSCRIPTION_ID " +
            "WHERE s.ORG_ID = ?";
}
