// Code generated by mockery v2.53.5. DO NOT EDIT.

package consentelement

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "github.com/wso2/openfgc/internal/consentelement/model"

	serviceerror "github.com/wso2/openfgc/internal/system/error/serviceerror"
)

// MockConsentElementService is an autogenerated mock type for the ConsentElementService type
type MockConsentElementService struct {
	mock.Mock
}

type MockConsentElementService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConsentElementService) EXPECT() *MockConsentElementService_Expecter {
	return &MockConsentElementService_Expecter{mock: &_m.Mock}
}

// CreateElementVersion provides a mock function with given fields: ctx, elementID, req, orgID
func (_m *MockConsentElementService) CreateElementVersion(ctx context.Context, elementID string, req model.ElementVersionCreateRequest, orgID string) (*model.ElementVersion, *serviceerror.ServiceError) {
	ret := _m.Called(ctx, elementID, req, orgID)

	if len(ret) == 0 {
		panic("no return value specified for CreateElementVersion")
	}

	var r0 *model.ElementVersion
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(context.Context, string, model.ElementVersionCreateRequest, string) (*model.ElementVersion, *serviceerror.ServiceError)); ok {
		return rf(ctx, elementID, req, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, model.ElementVersionCreateRequest, string) *model.ElementVersion); ok {
		r0 = rf(ctx, elementID, req, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ElementVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, model.ElementVersionCreateRequest, string) *serviceerror.ServiceError); ok {
		r1 = rf(ctx, elementID, req, orgID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// MockConsentElementService_CreateElementVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateElementVersion'
type MockConsentElementService_CreateElementVersion_Call struct {
	*mock.Call
}

// CreateElementVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - elementID string
//   - req model.ElementVersionCreateRequest
//   - orgID string
func (_e *MockConsentElementService_Expecter) CreateElementVersion(ctx interface{}, elementID interface{}, req interface{}, orgID interface{}) *MockConsentElementService_CreateElementVersion_Call {
	return &MockConsentElementService_CreateElementVersion_Call{Call: _e.mock.On("CreateElementVersion", ctx, elementID, req, orgID)}
}

func (_c *MockConsentElementService_CreateElementVersion_Call) Run(run func(ctx context.Context, elementID string, req model.ElementVersionCreateRequest, orgID string)) *MockConsentElementService_CreateElementVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.ElementVersionCreateRequest), args[3].(string))
	})
	return _c
}

func (_c *MockConsentElementService_CreateElementVersion_Call) Return(_a0 *model.ElementVersion, _a1 *serviceerror.ServiceError) *MockConsentElementService_CreateElementVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConsentElementService_CreateElementVersion_Call) RunAndReturn(run func(context.Context, string, model.ElementVersionCreateRequest, string) (*model.ElementVersion, *serviceerror.ServiceError)) *MockConsentElementService_CreateElementVersion_Call {
	_c.Call.Return(run)
	return _c
}

// CreateElementsInBatch provides a mock function with given fields: ctx, requests, orgID
func (_m *MockConsentElementService) CreateElementsInBatch(ctx context.Context, requests []model.ConsentElementCreateRequest, orgID string) (*model.BulkCreateResponse, *serviceerror.ServiceError) {
	ret := _m.Called(ctx, requests, orgID)

	if len(ret) == 0 {
		panic("no return value specified for CreateElementsInBatch")
	}

	var r0 *model.BulkCreateResponse
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(context.Context, []model.ConsentElementCreateRequest, string) (*model.BulkCreateResponse, *serviceerror.ServiceError)); ok {
		return rf(ctx, requests, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []model.ConsentElementCreateRequest, string) *model.BulkCreateResponse); ok {
		r0 = rf(ctx, requests, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.BulkCreateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []model.ConsentElementCreateRequest, string) *serviceerror.ServiceError); ok {
		r1 = rf(ctx, requests, orgID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// MockConsentElementService_CreateElementsInBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateElementsInBatch'
type MockConsentElementService_CreateElementsInBatch_Call struct {
	*mock.Call
}

// CreateElementsInBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - requests []model.ConsentElementCreateRequest
//   - orgID string
func (_e *MockConsentElementService_Expecter) CreateElementsInBatch(ctx interface{}, requests interface{}, orgID interface{}) *MockConsentElementService_CreateElementsInBatch_Call {
	return &MockConsentElementService_CreateElementsInBatch_Call{Call: _e.mock.On("CreateElementsInBatch", ctx, requests, orgID)}
}

func (_c *MockConsentElementService_CreateElementsInBatch_Call) Run(run func(ctx context.Context, requests []model.ConsentElementCreateRequest, orgID string)) *MockConsentElementService_CreateElementsInBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]model.ConsentElementCreateRequest), args[2].(string))
	})
	return _c
}

func (_c *MockConsentElementService_CreateElementsInBatch_Call) Return(_a0 *model.BulkCreateResponse, _a1 *serviceerror.ServiceError) *MockConsentElementService_CreateElementsInBatch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConsentElementService_CreateElementsInBatch_Call) RunAndReturn(run func(context.Context, []model.ConsentElementCreateRequest, string) (*model.BulkCreateResponse, *serviceerror.ServiceError)) *MockConsentElementService_CreateElementsInBatch_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteElementVersion provides a mock function with given fields: ctx, elementID, version, orgID
func (_m *MockConsentElementService) DeleteElementVersion(ctx context.Context, elementID string, version int, orgID string) *serviceerror.ServiceError {
	ret := _m.Called(ctx, elementID, version, orgID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteElementVersion")
	}

	var r0 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(context.Context, string, int, string) *serviceerror.ServiceError); ok {
		r0 = rf(ctx, elementID, version, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serviceerror.ServiceError)
		}
	}

	return r0
}

// MockConsentElementService_DeleteElementVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteElementVersion'
type MockConsentElementService_DeleteElementVersion_Call struct {
	*mock.Call
}

// DeleteElementVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - elementID string
//   - version int
//   - orgID string
func (_e *MockConsentElementService_Expecter) DeleteElementVersion(ctx interface{}, elementID interface{}, version interface{}, orgID interface{}) *MockConsentElementService_DeleteElementVersion_Call {
	return &MockConsentElementService_DeleteElementVersion_Call{Call: _e.mock.On("DeleteElementVersion", ctx, elementID, version, orgID)}
}

func (_c *MockConsentElementService_DeleteElementVersion_Call) Run(run func(ctx context.Context, elementID string, version int, orgID string)) *MockConsentElementService_DeleteElementVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(string))
	})
	return _c
}

func (_c *MockConsentElementService_DeleteElementVersion_Call) Return(_a0 *serviceerror.ServiceError) *MockConsentElementService_DeleteElementVersion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConsentElementService_DeleteElementVersion_Call) RunAndReturn(run func(context.Context, string, int, string) *serviceerror.ServiceError) *MockConsentElementService_DeleteElementVersion_Call {
	_c.Call.Return(run)
	return _c
}

// GetElement provides a mock function with given fields: ctx, elementID, orgID
func (_m *MockConsentElementService) GetElement(ctx context.Context, elementID string, orgID string) (*model.ElementVersion, *serviceerror.ServiceError) {
	ret := _m.Called(ctx, elementID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetElement")
	}

	var r0 *model.ElementVersion
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.ElementVersion, *serviceerror.ServiceError)); ok {
		return rf(ctx, elementID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.ElementVersion); ok {
		r0 = rf(ctx, elementID, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ElementVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) *serviceerror.ServiceError); ok {
		r1 = rf(ctx, elementID, orgID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// MockConsentElementService_GetElement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetElement'
type MockConsentElementService_GetElement_Call struct {
	*mock.Call
}

// GetElement is a helper method to define mock.On call
//   - ctx context.Context
//   - elementID string
//   - orgID string
func (_e *MockConsentElementService_Expecter) GetElement(ctx interface{}, elementID interface{}, orgID interface{}) *MockConsentElementService_GetElement_Call {
	return &MockConsentElementService_GetElement_Call{Call: _e.mock.On("GetElement", ctx, elementID, orgID)}
}

func (_c *MockConsentElementService_GetElement_Call) Run(run func(ctx context.Context, elementID string, orgID string)) *MockConsentElementService_GetElement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockConsentElementService_GetElement_Call) Return(_a0 *model.ElementVersion, _a1 *serviceerror.ServiceError) *MockConsentElementService_GetElement_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConsentElementService_GetElement_Call) RunAndReturn(run func(context.Context, string, string) (*model.ElementVersion, *serviceerror.ServiceError)) *MockConsentElementService_GetElement_Call {
	_c.Call.Return(run)
	return _c
}

// GetElementVersion provides a mock function with given fields: ctx, elementID, version, orgID
func (_m *MockConsentElementService) GetElementVersion(ctx context.Context, elementID string, version int, orgID string) (*model.ElementVersion, *serviceerror.ServiceError) {
	ret := _m.Called(ctx, elementID, version, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetElementVersion")
	}

	var r0 *model.ElementVersion
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(context.Context, string, int, string) (*model.ElementVersion, *serviceerror.ServiceError)); ok {
		return rf(ctx, elementID, version, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, string) *model.ElementVersion); ok {
		r0 = rf(ctx, elementID, version, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ElementVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, string) *serviceerror.ServiceError); ok {
		r1 = rf(ctx, elementID, version, orgID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// MockConsentElementService_GetElementVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetElementVersion'
type MockConsentElementService_GetElementVersion_Call struct {
	*mock.Call
}

// GetElementVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - elementID string
//   - version int
//   - orgID string
func (_e *MockConsentElementService_Expecter) GetElementVersion(ctx interface{}, elementID interface{}, version interface{}, orgID interface{}) *MockConsentElementService_GetElementVersion_Call {
	return &MockConsentElementService_GetElementVersion_Call{Call: _e.mock.On("GetElementVersion", ctx, elementID, version, orgID)}
}

func (_c *MockConsentElementService_GetElementVersion_Call) Run(run func(ctx context.Context, elementID string, version int, orgID string)) *MockConsentElementService_GetElementVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(string))
	})
	return _c
}

func (_c *MockConsentElementService_GetElementVersion_Call) Return(_a0 *model.ElementVersion, _a1 *serviceerror.ServiceError) *MockConsentElementService_GetElementVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConsentElementService_GetElementVersion_Call) RunAndReturn(run func(context.Context, string, int, string) (*model.ElementVersion, *serviceerror.ServiceError)) *MockConsentElementService_GetElementVersion_Call {
	_c.Call.Return(run)
	return _c
}

// ListElementVersions provides a mock function with given fields: ctx, elementID, orgID
func (_m *MockConsentElementService) ListElementVersions(ctx context.Context, elementID string, orgID string) (*model.VersionListResponse, *serviceerror.ServiceError) {
	ret := _m.Called(ctx, elementID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for ListElementVersions")
	}

	var r0 *model.VersionListResponse
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.VersionListResponse, *serviceerror.ServiceError)); ok {
		return rf(ctx, elementID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.VersionListResponse); ok {
		r0 = rf(ctx, elementID, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.VersionListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) *serviceerror.ServiceError); ok {
		r1 = rf(ctx, elementID, orgID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// MockConsentElementService_ListElementVersions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListElementVersions'
type MockConsentElementService_ListElementVersions_Call struct {
	*mock.Call
}

// ListElementVersions is a helper method to define mock.On call
//   - ctx context.Context
//   - elementID string
//   - orgID string
func (_e *MockConsentElementService_Expecter) ListElementVersions(ctx interface{}, elementID interface{}, orgID interface{}) *MockConsentElementService_ListElementVersions_Call {
	return &MockConsentElementService_ListElementVersions_Call{Call: _e.mock.On("ListElementVersions", ctx, elementID, orgID)}
}

func (_c *MockConsentElementService_ListElementVersions_Call) Run(run func(ctx context.Context, elementID string, orgID string)) *MockConsentElementService_ListElementVersions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockConsentElementService_ListElementVersions_Call) Return(_a0 *model.VersionListResponse, _a1 *serviceerror.ServiceError) *MockConsentElementService_ListElementVersions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConsentElementService_ListElementVersions_Call) RunAndReturn(run func(context.Context, string, string) (*model.VersionListResponse, *serviceerror.ServiceError)) *MockConsentElementService_ListElementVersions_Call {
	_c.Call.Return(run)
	return _c
}

// ListElements provides a mock function with given fields: ctx, orgID, filters
func (_m *MockConsentElementService) ListElements(ctx context.Context, orgID string, filters model.ElementListFilters) (*model.ListResponse, *serviceerror.ServiceError) {
	ret := _m.Called(ctx, orgID, filters)

	if len(ret) == 0 {
		panic("no return value specified for ListElements")
	}

	var r0 *model.ListResponse
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(context.Context, string, model.ElementListFilters) (*model.ListResponse, *serviceerror.ServiceError)); ok {
		return rf(ctx, orgID, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, model.ElementListFilters) *model.ListResponse); ok {
		r0 = rf(ctx, orgID, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, model.ElementListFilters) *serviceerror.ServiceError); ok {
		r1 = rf(ctx, orgID, filters)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// MockConsentElementService_ListElements_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListElements'
type MockConsentElementService_ListElements_Call struct {
	*mock.Call
}

// ListElements is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - filters model.ElementListFilters
func (_e *MockConsentElementService_Expecter) ListElements(ctx interface{}, orgID interface{}, filters interface{}) *MockConsentElementService_ListElements_Call {
	return &MockConsentElementService_ListElements_Call{Call: _e.mock.On("ListElements", ctx, orgID, filters)}
}

func (_c *MockConsentElementService_ListElements_Call) Run(run func(ctx context.Context, orgID string, filters model.ElementListFilters)) *MockConsentElementService_ListElements_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.ElementListFilters))
	})
	return _c
}

func (_c *MockConsentElementService_ListElements_Call) Return(_a0 *model.ListResponse, _a1 *serviceerror.ServiceError) *MockConsentElementService_ListElements_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConsentElementService_ListElements_Call) RunAndReturn(run func(context.Context, string, model.ElementListFilters) (*model.ListResponse, *serviceerror.ServiceError)) *MockConsentElementService_ListElements_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConsentElementService creates a new instance of MockConsentElementService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConsentElementService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConsentElementService {
	mock := &MockConsentElementService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
