-- Database DDL for Event Notification Framework (MySQL)

-- TOPIC definition
CREATE TABLE IF NOT EXISTS `TOPIC` (
  `TOPIC_ID` varchar(64) NOT NULL,
  `ORG_ID` varchar(128) NOT NULL,
  `NAME` varchar(225) NOT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `STATUS` enum('active', 'deregistered') NOT NULL DEFAULT 'active',
  PRIMARY KEY (`TOPIC_ID`),
  UNIQUE KEY `UQ_TOPIC_ORG_NAME` (`ORG_ID`, `NAME`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- EVENT definition
CREATE TABLE IF NOT EXISTS `EVENT` (
  `EVENT_ID` varchar(64) NOT NULL,
  `ORG_ID` varchar(128) NOT NULL,
  `GROUP_ID` varchar(128) NOT NULL,
  `TOPIC_ID` varchar(64) NOT NULL,
  `PAYLOAD` json NOT NULL,
  `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`EVENT_ID`),
  KEY `FK_E_TOPIC` (`TOPIC_ID`),
  KEY `IDX_EVENT_ORG_GROUP_TOPIC_CREATED` (`ORG_ID`, `GROUP_ID`, `TOPIC_ID`, `CREATED_AT`),
  CONSTRAINT `FK_E_TOPIC` FOREIGN KEY (`TOPIC_ID`) REFERENCES `TOPIC` (`TOPIC_ID`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- EVENT_PURPOSE definition
CREATE TABLE IF NOT EXISTS `EVENT_PURPOSE` (
  `EVENT_ID` varchar(64) NOT NULL,
  `PURPOSE_NAME` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  PRIMARY KEY (`EVENT_ID`, `PURPOSE_NAME`),
  KEY `IDX_EVENT_PURPOSE_NAME` (`PURPOSE_NAME`),
  CONSTRAINT `FK_EVENT_PURPOSES_EVENT` FOREIGN KEY (`EVENT_ID`) REFERENCES `EVENT` (`EVENT_ID`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- SUBSCRIPTION definition
CREATE TABLE IF NOT EXISTS `SUBSCRIPTION` (
  `SUBSCRIPTION_ID` varchar(64) NOT NULL,
  `ORG_ID` varchar(128) NOT NULL,
  `GROUP_ID` varchar(128) NOT NULL,
  `TOPIC_ID` varchar(64) NOT NULL,
  `STATUS` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'active',
  `PURPOSE_FILTER_MODE` varchar(32) NOT NULL,
  `CALLBACK_URL` varchar(512) DEFAULT NULL,
  `SHARED_SECRET` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `DELIVERY_MODE` varchar(32) NOT NULL,
  PRIMARY KEY (`SUBSCRIPTION_ID`),
  KEY `IDX_SUB_STATUS_UPDATED` (`STATUS`, `UPDATED_AT`),
  KEY `FK_S_TOPIC` (`TOPIC_ID`),
  KEY `IDX_SUB_MATCHING` (`ORG_ID`, `GROUP_ID`, `TOPIC_ID`, `STATUS`),
  CONSTRAINT `FK_S_TOPIC` FOREIGN KEY (`TOPIC_ID`) REFERENCES `TOPIC` (`TOPIC_ID`),
  CONSTRAINT `CHK_S_STATUS` CHECK ((`STATUS` in (_utf8mb4'active', _utf8mb4'pending', _utf8mb4'stale', _utf8mb4'deleted'))),
  CONSTRAINT `CHK_SM_DELIVERY_MODE` CHECK ((`DELIVERY_MODE` in (_utf8mb4'webhook', _utf8mb4'poll', _utf8mb4'pull')))
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- SUBSCRIPTION_PURPOSE definition
CREATE TABLE IF NOT EXISTS `SUBSCRIPTION_PURPOSE` (
  `SUBSCRIPTION_ID` varchar(64) NOT NULL,
  `PURPOSE_NAME` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  PRIMARY KEY (`SUBSCRIPTION_ID`, `PURPOSE_NAME`),
  KEY `IDX_SUB_PURPOSE_NAME` (`PURPOSE_NAME`),
  CONSTRAINT `FK_SUBSCRIPTION_PURPOSES_SUBSCRIPTION` FOREIGN KEY (`SUBSCRIPTION_ID`) REFERENCES `SUBSCRIPTION` (`SUBSCRIPTION_ID`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- WEBHOOK_DELIVERY definition
CREATE TABLE IF NOT EXISTS `WEBHOOK_DELIVERY` (
  `DELIVERY_ID` varchar(64) NOT NULL,
  `SUBSCRIPTION_ID` varchar(64) NOT NULL,
  `EVENT_ID` varchar(64) NOT NULL,
  `STATUS` varchar(32) NOT NULL DEFAULT 'pending',
  `ATTEMPT_COUNT` int NOT NULL DEFAULT '0',
  `NEXT_RETRY_AT` timestamp NULL DEFAULT NULL,
  `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `DELIVERED_AT` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`DELIVERY_ID`),
  UNIQUE KEY `UQ_EDP_EVENT_SUB` (`EVENT_ID`, `SUBSCRIPTION_ID`),
  KEY `FK_EDP_SUB` (`SUBSCRIPTION_ID`),
  CONSTRAINT `FK_EDP_EVENT` FOREIGN KEY (`EVENT_ID`) REFERENCES `EVENT` (`EVENT_ID`),
  CONSTRAINT `FK_EDP_SUB` FOREIGN KEY (`SUBSCRIPTION_ID`) REFERENCES `SUBSCRIPTION` (`SUBSCRIPTION_ID`),
  CONSTRAINT `CHK_WEBHOOK_DELIVERY_STATUS` CHECK ((`STATUS` in (_utf8mb4'pending', _utf8mb4'delivered', _utf8mb4'completed', _utf8mb4'failed')))
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- WEBHOOK_DELIVERY_ACK definition
CREATE TABLE IF NOT EXISTS `WEBHOOK_DELIVERY_ACK` (
  `ACK_ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `DELIVERY_ID` varchar(64) NOT NULL,
  `COMPLETED_AT` timestamp NULL DEFAULT NULL,
  `COMPLETION_STATUS` varchar(32) NOT NULL,
  `COMPLETION_EVIDENCE` varchar(512) NOT NULL,
  PRIMARY KEY (`ACK_ID`),
  UNIQUE KEY `UQ_EDA_DELIVERY` (`DELIVERY_ID`),
  KEY `IDX_EDA_COMPLETION_STATUS` (`COMPLETION_STATUS`),
  KEY `IDX_EDA_DELIVERY` (`DELIVERY_ID`),
  CONSTRAINT `FK_EDA_DELIVERY` FOREIGN KEY (`DELIVERY_ID`) REFERENCES `WEBHOOK_DELIVERY` (`DELIVERY_ID`),
  CONSTRAINT `CHK_EDA_COMPLETION_STATUS` CHECK ((`COMPLETION_STATUS` in (_utf8mb4'completed', _utf8mb4'disputed', _utf8mb4'partial')))
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- WEBHOOK_DELIVERY_AUDIT definition
CREATE TABLE IF NOT EXISTS `WEBHOOK_DELIVERY_AUDIT` (
  `AUDIT_ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `EVENT_ID` varchar(64) DEFAULT NULL,
  `DELIVERY_ID` varchar(64) DEFAULT NULL,
  `ORG_ID` varchar(128) NOT NULL,
  `RESPONSE_CODE` varchar(16) DEFAULT NULL,
  `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ATTEMPT_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`AUDIT_ID`),
  KEY `IDX_EA_DELIVERY` (`DELIVERY_ID`, `ATTEMPT_AT`),
  KEY `IDX_EA_EVENT` (`EVENT_ID`),
  CONSTRAINT `FK_EA_DELIVERY` FOREIGN KEY (`DELIVERY_ID`) REFERENCES `WEBHOOK_DELIVERY` (`DELIVERY_ID`) ON DELETE SET NULL,
  CONSTRAINT `FK_EA_EVENT` FOREIGN KEY (`EVENT_ID`) REFERENCES `EVENT` (`EVENT_ID`) ON DELETE SET NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- POLL_DELIVERY definition
CREATE TABLE IF NOT EXISTS `POLL_DELIVERY` (
  `DELIVERY_ID` varchar(64) NOT NULL,
  `SUBSCRIPTION_ID` varchar(64) NOT NULL,
  `EVENT_ID` varchar(64) NOT NULL,
  `STATUS` varchar(32) NOT NULL DEFAULT 'pending',
  `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `COMPLETED_AT` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`DELIVERY_ID`),
  UNIQUE KEY `UQ_EDPL_EVENT_SUB` (`EVENT_ID`, `SUBSCRIPTION_ID`),
  KEY `FK_EDPL_SUB` (`SUBSCRIPTION_ID`),
  CONSTRAINT `FK_EDPL_EVENT` FOREIGN KEY (`EVENT_ID`) REFERENCES `EVENT` (`EVENT_ID`),
  CONSTRAINT `FK_EDPL_SUB` FOREIGN KEY (`SUBSCRIPTION_ID`) REFERENCES `SUBSCRIPTION` (`SUBSCRIPTION_ID`),
  CONSTRAINT `CHK_POLL_DELIVERY_STATUS` CHECK ((`STATUS` in (_utf8mb4'pending', _utf8mb4'acknowledged', _utf8mb4'err')))
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;
