-- Consent Management API Database Schema (PostgreSQL)

-- Main consent table
CREATE TABLE IF NOT EXISTS CONSENT (
  CONSENT_ID            CHAR(36) NOT NULL,
  CREATED_TIME          BIGINT NOT NULL,
  UPDATED_TIME          BIGINT NOT NULL,
  GROUP_ID              VARCHAR(255) NOT NULL,
  CONSENT_TYPE          VARCHAR(64) NOT NULL,
  CURRENT_STATUS        VARCHAR(64) NOT NULL,
  CONSENT_FREQUENCY     INT DEFAULT NULL,
  EXPIRATION_TIME       BIGINT DEFAULT NULL,
  RECURRING_INDICATOR   BOOLEAN DEFAULT NULL,
  DATA_ACCESS_VALIDITY_DURATION BIGINT DEFAULT NULL,
  ORG_ID                VARCHAR(255) NOT NULL DEFAULT 'DEFAULT_ORG',
  PRIMARY KEY (CONSENT_ID)
);

CREATE INDEX IF NOT EXISTS idx_consent_group_id      ON CONSENT (GROUP_ID);
CREATE INDEX IF NOT EXISTS idx_consent_type          ON CONSENT (CONSENT_TYPE);
CREATE INDEX IF NOT EXISTS idx_consent_current_status ON CONSENT (CURRENT_STATUS);
CREATE INDEX IF NOT EXISTS idx_consent_created_time  ON CONSENT (CREATED_TIME);
CREATE INDEX IF NOT EXISTS idx_consent_updated_time  ON CONSENT (UPDATED_TIME);
CREATE INDEX IF NOT EXISTS idx_consent_org_id        ON CONSENT (ORG_ID);

-- Authorization resource table
CREATE TABLE IF NOT EXISTS CONSENT_AUTH_RESOURCE (
  AUTH_ID           CHAR(36) NOT NULL,
  CONSENT_ID        CHAR(36) NOT NULL,
  AUTH_TYPE         VARCHAR(255) NOT NULL,
  USER_ID           VARCHAR(255) DEFAULT NULL,
  AUTH_STATUS       VARCHAR(255) NOT NULL,
  UPDATED_TIME      BIGINT NOT NULL,
  RESOURCES         BYTEA DEFAULT NULL,
  ORG_ID            VARCHAR(255) NOT NULL DEFAULT 'DEFAULT_ORG',
  PRIMARY KEY (AUTH_ID),
  CONSTRAINT FK_CONSENT_AUTH_RESOURCE
    FOREIGN KEY (CONSENT_ID)
    REFERENCES CONSENT (CONSENT_ID)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_auth_resource_consent_id  ON CONSENT_AUTH_RESOURCE (CONSENT_ID);
CREATE INDEX IF NOT EXISTS idx_auth_resource_user_id     ON CONSENT_AUTH_RESOURCE (USER_ID);
CREATE INDEX IF NOT EXISTS idx_auth_resource_auth_status ON CONSENT_AUTH_RESOURCE (AUTH_STATUS);
CREATE INDEX IF NOT EXISTS idx_auth_resource_org_id      ON CONSENT_AUTH_RESOURCE (ORG_ID);

-- Status audit table for tracking consent status changes
CREATE TABLE IF NOT EXISTS CONSENT_STATUS_AUDIT (
  STATUS_AUDIT_ID   CHAR(36) NOT NULL,
  CONSENT_ID        CHAR(36) NOT NULL,
  CURRENT_STATUS    VARCHAR(64) NOT NULL,
  ACTION_TIME       BIGINT NOT NULL,
  REASON            TEXT DEFAULT NULL,
  ACTION_BY         VARCHAR(255) DEFAULT NULL,
  PREVIOUS_STATUS   VARCHAR(64) DEFAULT NULL,
  ORG_ID            VARCHAR(255) NOT NULL DEFAULT 'DEFAULT_ORG',
  PRIMARY KEY (STATUS_AUDIT_ID),
  CONSTRAINT FK_CONSENT_STATUS_AUDIT
    FOREIGN KEY (CONSENT_ID)
    REFERENCES CONSENT (CONSENT_ID)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_status_audit_consent_id  ON CONSENT_STATUS_AUDIT (CONSENT_ID);
CREATE INDEX IF NOT EXISTS idx_status_audit_action_time ON CONSENT_STATUS_AUDIT (ACTION_TIME);

-- Full consent history table for pre-mutation consent snapshots
CREATE TABLE IF NOT EXISTS CONSENT_HISTORY (
  HISTORY_ID       CHAR(36)     NOT NULL,
  CONSENT_ID       CHAR(36)     NOT NULL,
  ORG_ID           VARCHAR(255) NOT NULL DEFAULT 'DEFAULT_ORG',
  ACTION_TIME      BIGINT       NOT NULL,
  ACTION_BY        VARCHAR(255) DEFAULT NULL,
  REASON           VARCHAR(255) DEFAULT NULL,
  SNAPSHOT         JSONB        NOT NULL,

  PRIMARY KEY (HISTORY_ID),

  CONSTRAINT FK_CONSENT_HISTORY
    FOREIGN KEY (CONSENT_ID)
    REFERENCES CONSENT (CONSENT_ID)
    ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_history_consent_time ON CONSENT_HISTORY (CONSENT_ID, ACTION_TIME);
CREATE INDEX IF NOT EXISTS idx_history_org_id       ON CONSENT_HISTORY (ORG_ID);

-- Consent attributes table for key-value pairs
CREATE TABLE IF NOT EXISTS CONSENT_ATTRIBUTE (
  CONSENT_ID        CHAR(36) NOT NULL,
  ATT_KEY           VARCHAR(255) NOT NULL,
  ATT_VALUE         VARCHAR(1024) NOT NULL,
  ORG_ID            VARCHAR(255) NOT NULL DEFAULT 'DEFAULT_ORG',
  PRIMARY KEY (CONSENT_ID, ATT_KEY),
  CONSTRAINT FK_CONSENT_ATTRIBUTE
    FOREIGN KEY (CONSENT_ID)
    REFERENCES CONSENT (CONSENT_ID)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_consent_attribute_att_key ON CONSENT_ATTRIBUTE (ATT_KEY);
CREATE INDEX IF NOT EXISTS idx_consent_attribute_org_id  ON CONSENT_ATTRIBUTE (ORG_ID);

-- Consent element table — each row is a specific version of an element.
-- ID groups all versions of the same element (application-assigned UUID, never reused).
-- NAME+NAMESPACE uniqueness per org is enforced at the application layer;
-- C2 provides a partial DB-level guard at the version granularity.
CREATE TABLE IF NOT EXISTS ELEMENT (
  VERSION_ID     CHAR(36) NOT NULL,
  ID             CHAR(36) NOT NULL,
  NAME           VARCHAR(255) NOT NULL,
  NAMESPACE      VARCHAR(255) NOT NULL DEFAULT 'default',
  TYPE           VARCHAR(64) NOT NULL DEFAULT 'basic',
  VERSION        INTEGER NOT NULL,
  DISPLAY_NAME   VARCHAR(255) DEFAULT NULL,
  DESCRIPTION    VARCHAR(1024) DEFAULT NULL,
  ELEMENT_SCHEMA TEXT DEFAULT NULL,
  CREATED_TIME   BIGINT NOT NULL,
  ORG_ID         VARCHAR(255) NOT NULL DEFAULT 'DEFAULT_ORG',
  PRIMARY KEY (VERSION_ID),
  CONSTRAINT uk_element_id_version      UNIQUE (ORG_ID, ID, VERSION),
  CONSTRAINT uk_element_name_ns_version UNIQUE (ORG_ID, NAME, NAMESPACE, VERSION)
);

CREATE INDEX IF NOT EXISTS idx_element_id        ON ELEMENT (ID);
CREATE INDEX IF NOT EXISTS idx_element_name      ON ELEMENT (NAME);
CREATE INDEX IF NOT EXISTS idx_element_namespace ON ELEMENT (NAMESPACE);
CREATE INDEX IF NOT EXISTS idx_element_type      ON ELEMENT (TYPE);
CREATE INDEX IF NOT EXISTS idx_element_org_id    ON ELEMENT (ORG_ID);

-- Properties for element versions (key/value pairs scoped to element version)
CREATE TABLE IF NOT EXISTS ELEMENT_PROPERTY (
  ELEMENT_VERSION_ID  CHAR(36) NOT NULL,
  ATT_KEY             VARCHAR(255) NOT NULL,
  ATT_VALUE           VARCHAR(1024) NOT NULL,
  ORG_ID              VARCHAR(255) NOT NULL DEFAULT 'DEFAULT_ORG',
  PRIMARY KEY (ELEMENT_VERSION_ID, ATT_KEY),
  CONSTRAINT FK_ELEMENT_PROPERTY
    FOREIGN KEY (ELEMENT_VERSION_ID)
    REFERENCES ELEMENT (VERSION_ID)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_element_property_att_key ON ELEMENT_PROPERTY (ATT_KEY);
CREATE INDEX IF NOT EXISTS idx_element_property_org_id  ON ELEMENT_PROPERTY (ORG_ID);

-- Purpose table — each row is a specific version of a purpose.
-- ID groups all versions of the same purpose (application-assigned UUID, never reused).
-- NAME+GROUP_ID uniqueness per org is enforced at the application layer;
-- C2 provides a partial DB-level guard at the version granularity.
CREATE TABLE IF NOT EXISTS PURPOSE (
  VERSION_ID     CHAR(36) NOT NULL,
  ID             CHAR(36) NOT NULL,
  NAME           VARCHAR(255) NOT NULL,
  GROUP_ID       VARCHAR(255) NOT NULL,
  VERSION        INTEGER NOT NULL,
  DISPLAY_NAME   VARCHAR(255) DEFAULT NULL,
  DESCRIPTION    VARCHAR(1024) DEFAULT NULL,
  CREATED_TIME   BIGINT NOT NULL,
  ORG_ID         VARCHAR(255) NOT NULL DEFAULT 'DEFAULT_ORG',
  PRIMARY KEY (VERSION_ID),
  CONSTRAINT uk_purpose_id_version        UNIQUE (ORG_ID, ID, VERSION),
  CONSTRAINT uk_purpose_name_group_version UNIQUE (ORG_ID, NAME, GROUP_ID, VERSION)
);

CREATE INDEX IF NOT EXISTS idx_purpose_id        ON PURPOSE (ID);
CREATE INDEX IF NOT EXISTS idx_purpose_name      ON PURPOSE (NAME);
CREATE INDEX IF NOT EXISTS idx_purpose_group_id  ON PURPOSE (GROUP_ID);
CREATE INDEX IF NOT EXISTS idx_purpose_org_id    ON PURPOSE (ORG_ID);
CREATE INDEX IF NOT EXISTS idx_purpose_org_group ON PURPOSE (ORG_ID, GROUP_ID);

-- Properties for purpose versions (key/value pairs scoped to purpose version)
CREATE TABLE IF NOT EXISTS PURPOSE_PROPERTY (
  PURPOSE_VERSION_ID  CHAR(36) NOT NULL,
  ATT_KEY             VARCHAR(255) NOT NULL,
  ATT_VALUE           VARCHAR(1024) NOT NULL,
  ORG_ID              VARCHAR(255) NOT NULL DEFAULT 'DEFAULT_ORG',
  PRIMARY KEY (PURPOSE_VERSION_ID, ATT_KEY),
  CONSTRAINT FK_PURPOSE_PROPERTY
    FOREIGN KEY (PURPOSE_VERSION_ID)
    REFERENCES PURPOSE (VERSION_ID)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_purpose_property_att_key ON PURPOSE_PROPERTY (ATT_KEY);
CREATE INDEX IF NOT EXISTS idx_purpose_property_org_id  ON PURPOSE_PROPERTY (ORG_ID);

-- Maps element versions to purpose versions with mandatory flag (defines versioned purpose structure)
CREATE TABLE IF NOT EXISTS PURPOSE_ELEMENT_MAPPING (
  PURPOSE_VERSION_ID   CHAR(36) NOT NULL,
  ELEMENT_VERSION_ID   CHAR(36) NOT NULL,
  MANDATORY            BOOLEAN NOT NULL DEFAULT FALSE,
  ORG_ID               VARCHAR(255) NOT NULL DEFAULT 'DEFAULT_ORG',
  PRIMARY KEY (PURPOSE_VERSION_ID, ELEMENT_VERSION_ID),
  CONSTRAINT fk_purpose_element_purpose_ver
    FOREIGN KEY (PURPOSE_VERSION_ID)
    REFERENCES PURPOSE (VERSION_ID)
    ON DELETE CASCADE,
  CONSTRAINT fk_purpose_element_element_ver
    FOREIGN KEY (ELEMENT_VERSION_ID)
    REFERENCES ELEMENT (VERSION_ID)
    ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_purpose_element_purpose_ver ON PURPOSE_ELEMENT_MAPPING (PURPOSE_VERSION_ID);
CREATE INDEX IF NOT EXISTS idx_purpose_element_element_ver ON PURPOSE_ELEMENT_MAPPING (ELEMENT_VERSION_ID);
CREATE INDEX IF NOT EXISTS idx_purpose_element_org_id      ON PURPOSE_ELEMENT_MAPPING (ORG_ID);

-- Maps consents to the specific purpose version they were created against
CREATE TABLE IF NOT EXISTS PURPOSE_CONSENT_MAPPING (
  CONSENT_ID         CHAR(36) NOT NULL,
  PURPOSE_VERSION_ID CHAR(36) NOT NULL,
  ORG_ID             VARCHAR(255) NOT NULL DEFAULT 'DEFAULT_ORG',
  PRIMARY KEY (CONSENT_ID, PURPOSE_VERSION_ID),
  CONSTRAINT fk_purpose_consent_consent
    FOREIGN KEY (CONSENT_ID)
    REFERENCES CONSENT (CONSENT_ID)
    ON DELETE CASCADE,
  CONSTRAINT fk_purpose_consent_purpose_ver
    FOREIGN KEY (PURPOSE_VERSION_ID)
    REFERENCES PURPOSE (VERSION_ID)
    ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_purpose_consent_consent     ON PURPOSE_CONSENT_MAPPING (CONSENT_ID);
CREATE INDEX IF NOT EXISTS idx_purpose_consent_purpose_ver ON PURPOSE_CONSENT_MAPPING (PURPOSE_VERSION_ID);
CREATE INDEX IF NOT EXISTS idx_purpose_consent_org_id      ON PURPOSE_CONSENT_MAPPING (ORG_ID);

-- Stores user approval status and value for each element version in a consent
CREATE TABLE IF NOT EXISTS CONSENT_ELEMENT_APPROVAL (
  CONSENT_ID          CHAR(36) NOT NULL,
  PURPOSE_VERSION_ID  CHAR(36) NOT NULL,
  ELEMENT_VERSION_ID  CHAR(36) NOT NULL,
  APPROVED            BOOLEAN NOT NULL DEFAULT FALSE,
  VALUE               BYTEA DEFAULT NULL,
  ORG_ID              VARCHAR(255) NOT NULL DEFAULT 'DEFAULT_ORG',
  PRIMARY KEY (CONSENT_ID, PURPOSE_VERSION_ID, ELEMENT_VERSION_ID),
  CONSTRAINT fk_approval_purpose_element_ver
    FOREIGN KEY (PURPOSE_VERSION_ID, ELEMENT_VERSION_ID)
    REFERENCES PURPOSE_ELEMENT_MAPPING (PURPOSE_VERSION_ID, ELEMENT_VERSION_ID)
    ON DELETE RESTRICT,
  CONSTRAINT fk_approval_consent_purpose_ver
    FOREIGN KEY (CONSENT_ID, PURPOSE_VERSION_ID)
    REFERENCES PURPOSE_CONSENT_MAPPING (CONSENT_ID, PURPOSE_VERSION_ID)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_approval_consent     ON CONSENT_ELEMENT_APPROVAL (CONSENT_ID);
CREATE INDEX IF NOT EXISTS idx_approval_purpose_ver ON CONSENT_ELEMENT_APPROVAL (PURPOSE_VERSION_ID);
CREATE INDEX IF NOT EXISTS idx_approval_element_ver ON CONSENT_ELEMENT_APPROVAL (ELEMENT_VERSION_ID);
CREATE INDEX IF NOT EXISTS idx_approval_status      ON CONSENT_ELEMENT_APPROVAL (APPROVED);
CREATE INDEX IF NOT EXISTS idx_approval_org_id      ON CONSENT_ELEMENT_APPROVAL (ORG_ID);

-- Grievance (complaint) management tables

CREATE TABLE IF NOT EXISTS GRIEVANCE (
  GRIEVANCE_ID          CHAR(36) NOT NULL,
  ORG_ID                VARCHAR(255) NOT NULL DEFAULT 'DEFAULT_ORG',
  USER_ID               VARCHAR(255) NOT NULL,
  REFERENCE_ID          VARCHAR(32) NOT NULL,
  CATEGORY              VARCHAR(64) NOT NULL,
  PRIORITY              VARCHAR(16) NOT NULL,
  STATUS                VARCHAR(32) NOT NULL,
  DESCRIPTION           TEXT NOT NULL,
  SUBMITTED_TIME        BIGINT NOT NULL,
  UPDATED_TIME          BIGINT NOT NULL,
  STATUTORY_DUE_TIME    BIGINT NOT NULL,
  PRIMARY KEY (GRIEVANCE_ID),
  CONSTRAINT uk_grievance_reference_id UNIQUE (ORG_ID, REFERENCE_ID)
);

CREATE INDEX IF NOT EXISTS idx_grievance_org_user ON GRIEVANCE (ORG_ID, USER_ID);
CREATE INDEX IF NOT EXISTS idx_grievance_org_status ON GRIEVANCE (ORG_ID, STATUS);

CREATE TABLE IF NOT EXISTS GRIEVANCE_TIMELINE_ENTRY (
  ENTRY_ID          CHAR(36) NOT NULL,
  ORG_ID            VARCHAR(255) NOT NULL DEFAULT 'DEFAULT_ORG',
  GRIEVANCE_ID      CHAR(36) NOT NULL,
  ENTRY_TYPE        VARCHAR(32) NOT NULL,
  VISIBILITY        VARCHAR(16) NOT NULL,
  ACTOR_USER_ID     VARCHAR(255) DEFAULT NULL,
  ACTOR_ROLE        VARCHAR(32) NOT NULL,
  MESSAGE           TEXT DEFAULT NULL,
  FROM_STATUS       VARCHAR(32) DEFAULT NULL,
  TO_STATUS         VARCHAR(32) DEFAULT NULL,
  CREATED_TIME      BIGINT NOT NULL,
  PRIMARY KEY (ENTRY_ID),
  CONSTRAINT FK_GRIEVANCE_TIMELINE_ENTRY
    FOREIGN KEY (GRIEVANCE_ID)
    REFERENCES GRIEVANCE (GRIEVANCE_ID)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_timeline_grievance_created ON GRIEVANCE_TIMELINE_ENTRY (ORG_ID, GRIEVANCE_ID, CREATED_TIME);

CREATE TABLE IF NOT EXISTS GRIEVANCE_ATTACHMENT (
  ATTACHMENT_ID       CHAR(36) NOT NULL,
  ORG_ID              VARCHAR(255) NOT NULL DEFAULT 'DEFAULT_ORG',
  GRIEVANCE_ID        CHAR(36) NOT NULL,
  TIMELINE_ENTRY_ID   CHAR(36) DEFAULT NULL,
  FILE_NAME           VARCHAR(255) NOT NULL,
  FILE_SIZE_BYTES     BIGINT NOT NULL,
  CONTENT_TYPE        VARCHAR(255) NOT NULL,
  FILE_DATA           BYTEA NOT NULL,
  CREATED_TIME        BIGINT NOT NULL,
  PRIMARY KEY (ATTACHMENT_ID),
  CONSTRAINT FK_GRIEVANCE_ATTACHMENT_GRIEVANCE
    FOREIGN KEY (GRIEVANCE_ID)
    REFERENCES GRIEVANCE (GRIEVANCE_ID)
    ON DELETE CASCADE,
  CONSTRAINT FK_GRIEVANCE_ATTACHMENT_TIMELINE_ENTRY
    FOREIGN KEY (TIMELINE_ENTRY_ID)
    REFERENCES GRIEVANCE_TIMELINE_ENTRY (ENTRY_ID)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_attachment_grievance_id ON GRIEVANCE_ATTACHMENT (GRIEVANCE_ID);
CREATE INDEX IF NOT EXISTS idx_attachment_timeline_entry_id ON GRIEVANCE_ATTACHMENT (TIMELINE_ENTRY_ID);

-- Backs atomic per-org-per-year sequential generation of GRIEVANCE.REFERENCE_ID (e.g. GRV-2026-00001)
CREATE TABLE IF NOT EXISTS GRIEVANCE_REFERENCE_COUNTER (
  ORG_ID          VARCHAR(255) NOT NULL,
  YEAR_VALUE      VARCHAR(4) NOT NULL,
  NEXT_SEQUENCE   BIGINT NOT NULL DEFAULT 1,
  PRIMARY KEY (ORG_ID, YEAR_VALUE)
);
